spring.mvc.view.prefix: classpath:/templates/
# 给返回的页面添加后缀名
spring.mvc.view.suffix: .html

#spring.resources.static-locations: classpath:/static/

spring:
    profiles:
      active: pro

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yukaiji.kjblog.dao.apper
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
