spring:
    datasource:
        url: jdbc:mysql://abc:3306/kj_blog
        username: root
        password: abc
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false
server:
  port: 80