spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/kj_blog
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false
server:
  port: 8080
